apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: nginx-ns
spec:
  selector:
    matchLabels:  
     app: nginx
  
  template:
    metadata:
      name: nginx-dmn-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-d-pod
        image: nginx:latest
        ports:
        - containerPort: 80  

