kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels: # Fixed "matchLables" to "matchLabels"
      app: nginx
  template:
    metadata:
      labels: # Fixed "lables" to "labels"
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 # Fixed indentation

